In [28]:
import numpy as np
import pandas as pd
%matplotlib inline
import random
from pprint import pprint
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix, f1_score
import timeit
import matplotlib.pyplot as plt
import dtreefunctions
from sklearn import tree
from sklearn import model_selection
import copy
from sklearn.metrics import roc_curve
from sklearn.metrics import roc_auc_score
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix, f1_score
from dtreefunctions import decision_tree_algorithm,decision_tree_predictions,train_test_split

In [29]:
df = pd.read_csv("breast-cancer.csv")
df["label"] = df.Class
df = df.drop("Class", axis=1)

column_names = []
for column in df.columns:
    name = column.replace("-", "_")
    column_names.append(name)
df.columns = column_names

CATE_FEATURES = df.iloc[:,:].select_dtypes('object').columns

df=df.replace('no-recurrence-events', 0)
df=df.replace('recurrence-events', 1)

df_sklearn=copy.deepcopy(df)

for i in CATE_FEATURES:
    df_sklearn[i] = pd.factorize(df[i])[0]

X=df_sklearn.drop("label", axis=1)
y=df_sklearn["label"]
df_sklearn.head(2)



age  menopause  tumor_size  inv_nodes  node_caps  deg_malig  breast  \
0    0          0           0          0          0          3       0   
1    1          0           1          0          0          2       1   

   breast_quad  irradiat  label  
0            0         0      0  
1            1         0      0

In [30]:
X_train, X_test, y_train, y_test = model_selection.train_test_split(X, y, test_size=0.33, random_state=42)

In [31]:
clf = tree.DecisionTreeClassifier()
clf = clf.fit(X_train, y_train)
y_pred = clf.predict(X_test)

print('SK learn Tree')
print(accuracy_score(y_test,y_pred))
print(classification_report(y_test,y_pred))
print(confusion_matrix(y_test,y_pred))



SK learn Tree
0.6421052631578947
              precision    recall  f1-score   support

           0       0.73      0.78      0.75        67
           1       0.38      0.32      0.35        28

    accuracy                           0.64        95
   macro avg       0.55      0.55      0.55        95
weighted avg       0.63      0.64      0.63        95

[[52 15]
 [19  9]]


In [32]:
tic=timeit.default_timer()

train_df, test_df = dtreefunctions.train_test_split(df, test_size=0.2)
mytree = dtreefunctions.decision_tree_algorithm(train_df, max_depth=4)
y_pred = dtreefunctions.decision_tree_predictions(test_df,mytree)
print('Our Tree')
print(accuracy_score(test_df.label,y_pred))
print(classification_report(test_df.label,y_pred))
print(confusion_matrix(test_df.label,y_pred))

print(f1_score(test_df.label,y_pred,average='macro'))
toc=timeit.default_timer()
print('Time:',toc - tic)    
 



Our Tree
0.6666666666666666
              precision    recall  f1-score   support

           0       0.67      0.94      0.78        36
           1       0.67      0.19      0.30        21

    accuracy                           0.67        57
   macro avg       0.67      0.57      0.54        57
weighted avg       0.67      0.67      0.60        57

[[34  2]
 [17  4]]
0.5389527458492975
Time: 0.09118706599838333


In [33]:
X_test_our = test_df.iloc[:,:-1]
y_test_our = test_df.iloc[:,-1]


index_accuracies = np.arange(1,21)
column_name=["Accuracies","f1score"]
df_result = pd.DataFrame({'Accuracies':accuracies, 'f1score':f1score})

In [34]:
from sklearn.ensemble import RandomForestClassifier

# Create the model with 100 trees
model = RandomForestClassifier(n_estimators=100, 
                               bootstrap = True,
                               max_features = 'sqrt')
# Fit on training data
model.fit(X_train, y_train)

# Actual class predictions
y_pred = model.predict(X_test)

print('Random Forest')
print(accuracy_score(y_test,y_pred))
print(classification_report(y_test,y_pred))
print(confusion_matrix(y_test,y_pred))


Random Forest
0.7368421052631579
              precision    recall  f1-score   support

           0       0.76      0.91      0.83        67
           1       0.60      0.32      0.42        28

    accuracy                           0.74        95
   macro avg       0.68      0.62      0.62        95
weighted avg       0.71      0.74      0.71        95

[[61  6]
 [19  9]]
